</div><!-- End content -->

<div id="footer">
Web Design Copyright (c) <a href="http://riyonuk.no-ip.org/">Donovan &quot;Riyonuk&quot; Hernandez</a> -
Content Copyright (c) released under GPL<br />
We support web standards - 
<a href="http://validator.w3.org/check/referer">XHTML</a> -
<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a><br />
Thousand Parsec, TP and the golden wreath logo are all trademarks of, MITHIS in Australia and Lee Begg in New Zealand. Some rights reserved<br />
</div><!-- End footer -->

</div><!-- End wrapper -->
</body></html>
