<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" dir="ltr" lang="en">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="Content-Language" content="en-us" />

<meta name="Author" content="Web Design Copyright (c) 2006 Donovan 'Riyonuk' Hernandez - http://riyonuk.no-ip.org/" />
<meta name="Copyright" content="" />
<meta name="Description" content="A framework for developing turn-based space empire building games" />
<meta name="Keywords" content="strategy, strategies, games, 4x, turn, free, open, source, stars, galactic, civilizations, space, linux" />
<meta name="Robots" content="All" />

<!--[if lt IE 7.]>
<script defer type="text/javascript" src="/tp/js/pngfix.js"></script>
<![endif]-->

<link rel="shortcut icon" href="/tp/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" media="screen" href="/tp/parsec.css" />
<link rel="alternate" type="application/rss+xml" title="Thousand Parsec News" href="http://www.thousandparsec.net/tp/rss.php" />

<title>Thousand Parsec : <?php echo $title ?></title>

</head>
<body>
<div id="wrapper">

<div id="banner">
	<h1>Thousand Parsec: <?php echo $title; ?></h1>
	<img src="/tp/img/logo_t.png" alt="Thousand Parsec Logo" />
</div>

<div id="content">
